---
# roles/redis/tasks/main.yml
# redis角色任务
# 安装redis
- include: redis.yaml
# 优化系统设置
- include: sysctl.yaml
# 使用supervisor进程管理工具配置redis app
- include: supervisor.yaml
# 创建快捷命令
- include: alias.yaml
# 根据是否定义REDIS_SENTINEL_APP_NAME环境变量决定是否要部署Redis哨兵模式
- name: Config redis sentinel tasks
  include_tasks: redis-sentinel.yaml
  when: REDIS_SENTINEL_APP_NAME is defined and REDIS_CLUSTER_APP_NAME is not defined
# 根据是否定义REDIS_CLUSTER_APP_NAME环境变量决定是否要部署Redis集群模式
- name: Config redis cluster tasks
  include_tasks: redis-cluster.yaml
  when: REDIS_SENTINEL_APP_NAME is not defined and REDIS_CLUSTER_APP_NAME is defined
