---
- name: Copy install shell file
  ansible.builtin.copy:
    src: "{{ MINICONDA_SHELL_FILENAME }}"
    dest: "/tmp/{{ MINICONDA_SHELL_FILENAME }}"
    force: yes
    backup: yes
    remote_src: no
    mode: u=rwx,g=r,o=r

# 归档文件复制到远程主机时，会自动解压
- name: Unarchive the source package
  ansible.builtin.unarchive:
    src: redis-stable.tar.gz
    dest: /tmp
    remote_src: no




    - result.rc != 0

- name: Copy condarc config file
  ansible.builtin.template:
    src: condarc.j2
    dest: "/root/.condarc"
    force: yes
    backup: yes
    remote_src: no

- name: Install miniconda
  ansible.builtin.command:
    # cmd: "/tmp/Miniconda3-py310_24.1.2-0-Linux-x86_64.sh -b -p /srv/miniconda3"
    cmd: "/tmp/{{ MINICONDA_SHELL_FILENAME }} -b -p {{ MINICONDA_BASE_DIR }}"
    # 如果对应的文件存在，则忽略此步
    creates: "{{ MINICONDA_BASE_DIR }}"

- name: Remove install shell file
  ansible.builtin.file:
    path: "/tmp/{{ MINICONDA_SHELL_FILENAME }}"
    state: absent
