---
- name: Copy redis app config
  ansible.builtin.template:
    src: redis.ini.j2
    dest: /etc/supervisord.d/redis.ini
    force: yes
    backup: yes
    remote_src: no

- name: Start service supervisord, in all cases
  ansible.builtin.service:
    name: supervisord
    state: restarted
    # 开机启动
    enabled: yes